In [9]:
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
from matplotlib.patches import Arc
import numpy as np

import json
import pickle
import pandas as pd

In [10]:
file = "./passShot.csv"

In [11]:
df = pd.read_csv(file)

In [12]:
df

Team  Passes  Shots  Goals  Matches  Danger Passes
0           Sweden Women's     384      8      1      NaN             10
1           Canada Women's     558     11      0      NaN             22
2         Cameroon Women's     369     22      2      NaN             47
3      New Zealand Women's     472      9      1      NaN             23
4          Germany Women's     463     12      3      NaN             27
..                     ...     ...    ...    ...      ...            ...
99         England Women's     496     16      3      NaN             42
100        England Women's     500      7      1      NaN             18
101  United States Women's     373     11      2      NaN             29
102    Netherlands Women's     644     16      1      NaN             41
103         Sweden Women's     501     11      0      NaN              8

[104 rows x 6 columns]

In [13]:
a_file = open("./danger_passes.pkl", "rb")
danger_passes_by = pickle.load(a_file)

In [16]:
danger_passes_by.keys()

dict_keys(["Sweden Women's", "Canada Women's", "Cameroon Women's", "New Zealand Women's", "Germany Women's", "Nigeria Women's", "England Women's", "Jamaica Women's", "Australia Women's", "Italy Women's", "Netherlands Women's", "France Women's", "Brazil Women's", "Scotland Women's", "Thailand Women's", "Japan Women's", "Korea Republic Women's", "Norway Women's", "United States Women's", "Chile Women's", "China PR Women's", "Spain Women's", "South Africa Women's", "Argentina Women's"])

In [32]:
#Make comparative pass maps
x_all=[]
y_all=[]
H_Pass=dict()

#Size of the pitch in yards (StatsBomb)
pitchLengthX = 120
pitchWidthY = 80

for team, value in danger_passes_by.items():
    
    dp=danger_passes_by[team]
    print(team + "- "+ str(len(dp)))
    
    x=[]
    y=[]
    for i,apass in dp.iterrows():
        x.append(apass['location'][0])
        y.append(pitchWidthY-apass['location'][1])

    #Make a histogram of passes
    H_Pass[team]=np.histogram2d(y, x,bins=5,range=[[0, pitchWidthY],[0, pitchLengthX]])
    
    x_all = x_all+x
    y_all = y_all+y

H_Pass_All=np.histogram2d(y_all, x_all,bins=5,range=[[0, pitchWidthY],[0, pitchLengthX]])

Sweden Women's- 238
Canada Women's- 160
Cameroon Women's- 96
New Zealand Women's- 41
Germany Women's- 165
Nigeria Women's- 61
England Women's- 231
Jamaica Women's- 48
Australia Women's- 133
Italy Women's- 116
Netherlands Women's- 239
France Women's- 199
Brazil Women's- 83
Scotland Women's- 52
Thailand Women's- 30
Japan Women's- 155
Korea Republic Women's- 108
Norway Women's- 149
United States Women's- 321
Chile Women's- 95
China PR Women's- 104
Spain Women's- 178
South Africa Women's- 36
Argentina Women's- 42


(array([[  1.,  56., 130., 214., 231.],
        [ 13.,  66., 131., 245., 178.],
        [ 27.,  49., 167., 220.,  87.],
        [ 12.,  60., 149., 266., 194.],
        [  4.,  52.,  91., 218., 216.]]),
 array([ 0., 16., 32., 48., 64., 80.]),
 array([  0.,  24.,  48.,  72.,  96., 120.]))

In [35]:
#Compare to mean

team_size = H_Pass.keys().size()
print(team_size)

n_col = 2
if team_size/2 == 0:
    n_col = 2

main = np.arange(team_size.size).reshape(-1, n_col)

# Layout format
# Eg. Title 1 row across 3 column length, Main, annot 1 row across 3 column length
layout = np.concatenate([ 
            np.tile(['title'], (1, main.shape[1])),
            main,
            np.tile(['annot'], (1, main.shape[1]))
        ])


height_ratios = np.repeat(1, main.shape[0]).tolist()
height_ratios.insert(0, 0.05)
height_ratios.append(0.05)

# Adding subplot 
fig, axd = plt.subplot_mosaic(layout,constrained_layout=True,figsize=(12, 2*main.shape[0]), 
                              gridspec_kw={'height_ratios':height_ratios})

# Filter title and annot from axd.values
main_dict = {k: v for k, v in axd.items() if (k != 'title' and k !='annot')}

#Size of the pitch in yards (StatsBomb)
pitchLengthX = 120
pitchWidthY = 80

# For every ax we call function draw_pitch with horizontal orientation 




for team in teams:
    (fig,ax) = createPitch(pitchLengthX,pitchWidthY,'yards','gray')
    pos=ax.imshow(H_Pass[team][0]/number_of_matches[team], aspect='auto',cmap=plt.cm.seismic,vmin=-3, vmax=3)
    pos=ax.imshow(H_Pass[team][0]/number_of_matches[team] - H_Pass_All[0]/(len(matches)*2), extent=[0,120,0,80], aspect='auto',cmap=plt.cm.seismic,vmin=-3, vmax=3)
    #pos=ax.imshow(H_Pass[team][0]/number_of_matches[team] / (H_Pass_All[0]/(len(matches)*2)), extent=[0,120,0,80], aspect='auto',cmap=plt.cm.seismic,vmin=0.5, vmax=2)
    
    ax.set_title('Number of passes per match by ' +team)
    plt.xlim((-1,121))
    plt.ylim((83,-3))
    plt.tight_layout()
    plt.gca().set_aspect('equal', adjustable='box')
    fig.colorbar(pos, ax=ax)
    plt.show()
    
    #fig.savefig('Output/PassHeat' + team+ '.pdf', dpi=None, bbox_inches="tight") 

AttributeError: 'dict_keys' object has no attribute 'size'